CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role INT,
    FOREIGN KEY (role) REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DELETE FROM roles;
DELETE FROM users;

